[general]
import = [
"~/.config/alacritty/solarized-dark-yz.toml",
]
[window]
opacity = 0.68
blur = true
[cursor]
style = { shape = "Beam" }
[colors.cursor]
cursor = "#64bc78"
[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { style = "Regular" }
offset = { x = 1, y = 4 }
glyph_offset = { y = 2 }
[selection]
save_to_clipboard = true
