#!/usr/bin/env bash

set -e

if [[ `uname` == Linux ]]; then
  CONFIG="install.conf/linux.yaml"
elif [[ `uname` == Darwin ]]; then
  CONFIG="install.conf/darwin.yaml"
elif [[ `uname` == *"MINGW"* || `uname` == *"MSYS"* || `uname` == *"CYGWIN"* ]]; then
  CONFIG="install.conf/windows.yaml"
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

(cd "${DOTBOT_DIR}" && git submodule update --init --recursive)
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
