gui:
  theme:
    selectedLineBgColor:
      - '#56635f'
    inactiveBorderColor:
      - '#999999'
    activeBorderColor:
      - '#017E70'
  spinner:
    frames:
      - ⠋
      - ⠙
      - ⠹
      - ⠸
      - ⠼
      - ⠴
      - ⠦
      - ⠧
      - ⠇
      - ⠏

customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
